---
title: "Amning"
author: "TT"
date: "2nd of February 2020"
output:
  html_document:
  theme: paper
highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = F)
```

```{r lib}
library(tidyverse)
library(lubridate)
library(glue)
library(ggtext)
library(showtext)
library(patchwork)

font_add_google("Roboto Mono", "Roboto Mono")
```

```{r ggplot theme}
theme_set(theme_minimal(base_family = "Roboto Mono", base_size = 9))
theme_update(axis.title = element_blank(),
             axis.ticks = element_blank(),
             legend.position = "bottom",
             legend.title = element_blank(),
             legend.spacing.x = unit(1, "inch"),
             legend.key = element_rect(color = NA),
             legend.key.height = unit(0.75, "lines"), 
             legend.key.width = unit(5, "lines"),
             plot.margin = margin(10,10,10,10))
```

```{r colors}
skin_col <- c("#E0728F",
              "#E696A3", #FDC0D3
              "#FDCECD") #FAE3D8

milk_col <- "#FFF9D6"

back_col <- "#72ADA7"

```

```{r load}
DAT_amning <- read_csv("amning.txt"
                       , col_names = c("Amning"))
```

```{r transform}
amning <- DAT_amning %>% 
  mutate(dato = ifelse(str_detect(Amning, "DØGN"), 
                       str_extract(Amning, "\\d+") %>% as.numeric(),
                       NA),
         dato = dmy("01-12-2019") + days(dato)) %>% 
  fill(dato) %>% 
  filter(!str_detect(Amning, "DØGN"),
         str_detect(Amning, "\\d")) %>% 
  mutate(tid = str_extract(Amning, "\\d+\\.\\d+"),
         varighed = str_extract(Amning, "(?<=\\()\\d+")) %>% 
  add_row(dato = c(.$dato %>% unique,max(.$dato) + days(1)), tid = "00.00", varighed = 0) %>% 
  arrange(dato, tid) %>% 
  mutate(dato_start = glue("{dato} {tid}") %>% ymd_hm(),
         dato_slut= dato_start + minutes(varighed),
         amn_int = dato_start %--% dato_slut,
         amn_dec = amn_int / hours(1),
         pau_int = dato_slut %--% lead(dato_start),
         pau_dec = pau_int / hours(1))

```

```{r fig_circle}
(
circle <- amning %>% 
  select(dato, amn_dec, pau_dec, tid) %>% 
  pivot_longer(amn_dec:pau_dec, names_to = "type", values_to = "value") %>% 
  filter(month(dato) == 1, 
         dato != max(dato),
         value > 0) %>% 
  add_row(dato = rep(seq(min(.$dato) - days(5),min(.$dato) - days(1), "days"), 20),
          type = ifelse(dato < min(.$dato) - days(3), "Inner", "Outer"), 
          value = 24/20) %>% 
  add_rownumber(dato) %>% 
  ggplot() +
    geom_col(aes(dato, 
                 value, 
                 fill = type, 
                 group = n),
             width = 0.5,
             show.legend = F) +
    labs(x = NULL,
         y = NULL) +
    coord_polar(theta = "y") +
    scale_y_continuous(breaks = seq(0,21,3),
                       labels = glue('{str_pad(seq(0,21,3), 2, "left", "0")}:00')) +
    scale_fill_manual(values = c(milk_col, skin_col)) + #c(milk_col, skin_col)
    theme(axis.text.y = element_blank(),
          panel.grid = element_blank())
 )
```

```{r fig_varighed}
varig <- amning %>% 
  filter(varighed > 0) %>% 
  ggplot(aes(varighed %>% as.numeric())) + 
    geom_density(aes(fill = month(dato, label = T)),
                 alpha = 0.4) +
    geom_density(aes(color = month(dato, label = T)),
                 size = 1,
                 show.legend = F) +
    guides(fill = guide_legend(title.position = "top", 
                               title.hjust = 0.5, nrow = 1,
                               label.position = "bottom",
                               override.aes = list(color = NA),
                               reverse = T))
```

```{r fig_antal}

antal <- amning %>% 
  filter(varighed > 0) %>% 
  group_by(dato) %>% 
  summarise(antal = n()) %>% 
  filter(antal< 20) %>% 
  ggplot() + 
    geom_density(aes(antal,
                     fill = month(dato, label = T), 
                     color = month(dato, label = T)), 
                 alpha = 0.4,
                 size = 1,
                 show.legend = F)
  

```

```{r fig_antal_var}
(
  amning %>% 
  filter(varighed > 0) %>% 
  group_by(dato) %>% 
  summarise(antal = n(),
            var = mean(as.numeric(varighed), na.rm = T),
            var_semin = var - sd(as.numeric(varighed)),
            var_semax = var + sd(as.numeric(varighed))) %>% 
  filter(antal< 20) %>% 
  ggplot() + 
    geom_col(aes(dato, var),
             alpha = 0.3) +
    geom_errorbar(aes(x = dato, ymin = var_semin, ymax = var_semax),
                  width = 0, size = 1, alpha = 0.4) +
    geom_smooth(aes(dato, antal),
                se = F) +
    geom_point(aes(dato, antal)) +
    scale_x_date(labels = label_date_short(), date_breaks = "1 month") +
    theme(panel.grid = element_blank(),
          axis.text.y = element_text())
  
)
```

```{r fig_circle_facet}

amning %>% 
  select(dato, amn_dec, pau_dec, tid) %>% 
  pivot_longer(amn_dec:pau_dec, names_to = "type", values_to = "value") %>% 
  filter(dato != max(dato),
         value > 0) %>% 
  group_by(md = floor_date(dato, "month")) %>% 
  mutate(day = cumsum((dato != lag(dato)) %>% replace_na(T))) %>% 
  ungroup() %>% 
  add_row(md = unique(.$md),
          day = list(0:-4),
          type = list(c("Outer","Outer","Outer","Inner","Inner")),
          dato = unique(.$md),
          value = 24) %>% 
  unnest() %>% 
  add_rownumber(dato) %>% 
  ggplot() +
    geom_col(aes(day, 
                 value, 
                 fill = type, 
                 group = n),
             width = 0.5,
             show.legend = F) +
    labs(x = NULL,
         y = NULL) +
    coord_polar(theta = "y") +
    facet_wrap(~md) +
    scale_y_continuous(breaks = seq(0,21,3),
                       labels = glue('{str_pad(seq(0,21,3), 2, "left", "0")}:00')) +
    scale_fill_manual(values = c(milk_col, skin_col)) + #c(milk_col, skin_col)
    theme(axis.text.y = element_blank(),
          panel.grid = element_blank())

```

```{r fig_final}
circle / 
  (plot_spacer() + varig + antal + plot_spacer() + plot_layout(widths = c(0.5,4,4,0.5))) + 
  plot_layout(height = c(5,1),
              guides = 'collect')

ggsave("AMN.PDF", dpi = 300, width = 10, height = 14.14)

```

